language: rust
script:
- echo "skipping tests..."
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: trusty
cache: cargo
services:
  - docker

jobs:
  include:
    - stage: test
      script: ./ci/test.sh
      if: branch != master
    - stage: deploy
      script: ./ci/deploy.sh
      if: branch = master