language: rust
script:
- echo "skipping tests..."
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: trusty
cache: cargo
services:
  - docker

jobs:
  include:
    - stage: test stable
      rust: stable
      script: ./ci/test.sh
      if: branch != master
    - stage: test beta
      rust: beta
      script: ./ci/test.sh
      if: branch != master
    - stage: test nightly
      rust: nightly
      script: ./ci/test.sh
      if: branch != master    
    - stage: deploy
      script: ./ci/deploy.sh
      if: branch = master