language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: trusty
cache: cargo
services:
  - docker

jobs:
  include:
    - stage: test
      script: ./ci/test.sh
      if: branch != master
    - stage: build docker image
      script:
      - echo "doing docker stuff....."
      if: branch = master