language: rust
before_script:
  - rustup component add clippy
  - cargo install --force cargo-audit
  - cargo install --force --git https://github.com/kbknapp/cargo-outdated
script:
  - cargo clippy
  - cargo audit
  - cargo outdated
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo