language: rust
script:
- echo "skipping tests..."
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
dist: trusty
cache: cargo
jobs:
  include:
    # tests
    - stage: test
      rust: stable
      script: ./ci/test.sh
      if: branch != master
    - stage: test
      rust: beta
      script: ./ci/test.sh
      if: branch != master
    - stage: test
      rust: nightly
      script: ./ci/test.sh
      if: branch != master    

    # build
    - stage: build
      rust: stable
      script: ./ci/build.sh
      if: branch != master

      # deploy    
    - stage: deploy
      services:
      - docker
      script: ./ci/deploy.sh
      if: branch = master